# Workflow configurations
workflows:
  content_editing:
    description: "Complete content editing workflow with feedback loop"
    agents:
      - file_processor
      - text_editor
      - feedback
    max_iterations: 2
    quality_threshold: 0.85

  sentiment_aware_editing:
    description: "Runs the content editing workflow and then analyzes the sentiment of the final result."
    agents:
      - file_processor
      - text_editor
      - feedback
      - sentiment
    max_iterations: 2
    quality_threshold: 0.85